# This is a complete configuration to deploy Loki backed by a s3-compatible API
# like MinIO for storage.
# Index files will be written locally at /loki/index and, eventually, will be shipped to the storage via tsdb-shipper.
target: backend
auth_enabled: false

server:
  http_listen_port: 3100
  grpc_listen_port: 9095

common:
  ring:
    kvstore:
      store: memberlist
    instance_addr: loki-backend
  replication_factor: 1
  path_prefix: /loki/backend/
#  instance_addr: loki-backend

memberlist:
  join_members: 
    - loki-read
    - loki-write


schema_config:
  configs:
  - from: 2020-05-15
    store: tsdb
    object_store: s3
    schema: v13
    index:
      prefix: index_
      period: 24h

#compactor:
#query_scheduler:


storage_config:
 tsdb_shipper:
   active_index_directory: /loki/index
   cache_location: /loki/index_cache
 aws:
   s3: s3://minioadmin:minioadmin@minio1.:9000/loki
   s3forcepathstyle: true
